"""criar tabelas4

Revision ID: 3166e0a80c9e
Revises: 1fad59d46f41
Create Date: 2026-04-28 16:35:25.859015

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3166e0a80c9e'
down_revision: Union[str, Sequence[str], None] = '1fad59d46f41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('produtos', sa.Column('descricao', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('produtos', 'descricao')
    # ### end Alembic commands ###
